# Generated by Django 4.2.7 on 2023-12-27 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('dateWork', models.DateField()),
                ('timeWork', models.TimeField()),
                ('evaluationStar', models.IntegerField()),
            ],
            options={
                'db_table': 'avocat',
            },
        ),
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'coordonnees',
            },
        ),
        migrations.CreateModel(
            name='Langues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'langues',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specialite',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visitor',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('cause', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.avocat')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.visitor')),
            ],
            options={
                'db_table': 'rendezvous',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimePub', models.DateTimeField()),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.avocat')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('coordonnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.coordonnees')),
            ],
            options={
                'db_table': 'phoneNumbers',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('rendezvous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avocat.rendezvous')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.avocat')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimePub', models.DateTimeField()),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.avocat')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.visitor')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='AvocatSpecialitePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.avocat')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.specialite')),
            ],
            options={
                'db_table': 'avocat_specialite_price',
            },
        ),
        migrations.AddField(
            model_name='avocat',
            name='coordonnees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.coordonnees'),
        ),
        migrations.AddField(
            model_name='avocat',
            name='langues',
            field=models.ManyToManyField(blank=True, to='avocat.langues'),
        ),
        migrations.AddField(
            model_name='avocat',
            name='specialitees',
            field=models.ManyToManyField(blank=True, related_name='avocats', through='avocat.AvocatSpecialitePrice', to='avocat.specialite'),
        ),
        migrations.AddField(
            model_name='avocat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
