# Generated by Django 4.2.7 on 2023-12-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0002_avocat_experiencework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocatspecialiteprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
