# Generated by Django 4.2.7 on 2023-12-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0003_alter_avocatspecialiteprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='evaluationStar',
            field=models.IntegerField(null=True),
        ),
    ]
