# Generated by Django 4.2.7 on 2023-12-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0005_avocat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='photo',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=''),
        ),
    ]
