# Generated by Django 4.2.7 on 2023-12-31 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0006_alter_avocat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='coordonnees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonenumbers', to='avocat.coordonnees'),
        ),
    ]
