# Generated by Django 4.2.7 on 2023-12-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0008_remove_post_created_alter_post_datetimepub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AlterField(
            model_name='comment',
            name='dateTimePub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
