# Generated by Django 4.2.7 on 2023-12-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0009_remove_comment_created_alter_comment_datetimepub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='lastName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
