# Generated by Django 4.2.7 on 2024-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0012_alter_avocat_evaluationstar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='adresse',
            field=models.CharField(max_length=1000),
        ),
    ]
