# Generated by Django 4.2.7 on 2024-01-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0013_alter_avocat_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='mapsAdr',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='adresse',
            field=models.CharField(max_length=100),
        ),
    ]
