# Generated by Django 4.2.7 on 2024-01-27 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0014_avocat_mapsadr_alter_avocat_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='evalutationAvocatVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluationStar', models.IntegerField(null=True)),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.avocat')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat.visitor')),
            ],
            options={
                'db_table': 'evalutationAvocatVisitor',
            },
        ),
    ]
