# Generated by Django 4.2.7 on 2024-01-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0015_evalutationavocatvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='coordonnees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avocat.coordonnees'),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='dateWork',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='langues',
            field=models.ManyToManyField(blank=True, null=True, to='avocat.langues'),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='specialitees',
            field=models.ManyToManyField(blank=True, null=True, related_name='avocats', through='avocat.AvocatSpecialitePrice', to='avocat.specialite'),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='timeWork',
            field=models.TimeField(null=True),
        ),
    ]
