# Generated by Django 4.2.7 on 2024-01-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0016_alter_avocat_coordonnees_alter_avocat_datework_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avocat',
            old_name='timeWork',
            new_name='timeWorkEnd',
        ),
        migrations.AddField(
            model_name='avocat',
            name='timeWorkStart',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='dateWork',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
    ]
