# Generated by Django 4.2.7 on 2024-01-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0017_rename_timework_avocat_timeworkend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='avocat',
            name='dateWork',
        ),
        migrations.AddField(
            model_name='avocat',
            name='dateWork',
            field=models.ManyToManyField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], null=True, to='avocat.dayofwork'),
        ),
    ]
