# Generated by Django 4.2.7 on 2024-01-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat', '0018_dayofwork_remove_avocat_datework_avocat_datework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avocat',
            name='dateWork',
        ),
        migrations.DeleteModel(
            name='DayOfWork',
        ),
        migrations.AddField(
            model_name='avocat',
            name='dateWork',
            field=models.CharField(default='all the days', max_length=200, null=True),
        ),
    ]
